services:
  config-server:
    build: ./microservices/config-server
    container_name: config-server
    ports:
      - "7777:7777"
    networks:
      - microservices-network
    restart: always
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7777/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  auth-service:
    build: ./microservices/auth-service
    container_name: auth-service
    ports:
      - "7076:7076"
    environment:
      - CONFIG_SERVER_URL=http://config-server:7777
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:7777
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/gestion-etudiants
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      - microservices-network
    restart: always
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7076/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  eureka-server:
    build: ./microservices/eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:7777
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - microservices-network
    restart: always
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  gateway-server:
    build: ./microservices/gateway-server
    container_name: gateway-server
    ports:
      - "7070:7070"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - CONFIG_SERVER_URL=http://config-server:7777
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:7777
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      - microservices-network
    restart: always
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7070/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.0
    container_name: keycloak
    command: start-dev
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  keycloak_data:
