services:
  # Config Server
  config-server:
    build: ./microservices/config-server
    container_name: config-server
    ports:
      - "7777:7777"
    networks:
      - microservices-network
    restart: always
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7777/actuator/health" ]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 40s

  # Eureka Server
  eureka-server:
    build: ./microservices/eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:7777
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - microservices-network
    restart: always
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Gateway
  gateway-server:
    build: ./microservices/gateway-server
    container_name: gateway-server
    ports:
      - "7070:7070"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      - microservices-network
    restart: always
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7070/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Microservice Scolarité
  scolarite-service:
    build: ./microservices/ms-scolarite
    container_name: scolarite-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://scolarite-mysql:3306/scolarite_db
      SPRING_DATASOURCE_USERNAME: scolarite
      SPRING_DATASOURCE_PASSWORD: scolarite
      SPRING_PROFILES_ACTIVE: docker
      #      SPRING_CLOUD_CONFIG_URI: http://config-server:7777
      SPRING_CLOUD_CONFIG_ENABLED: "false"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - scolarite-mysql
      - config-server
      - eureka-server
    networks:
      - microservices-network
    restart: always
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8082/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Base MySQL pour Scolarité
  scolarite-mysql:
    image: mysql:8
    container_name: scolarite-mysql
    environment:
      MYSQL_DATABASE: scolarite_db
      MYSQL_USER: scolarite
      MYSQL_PASSWORD: scolarite
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - scolarite-mysql-data:/var/lib/mysql
    networks:
      - microservices-network
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot" ]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  scolarite-mysql-data:


networks:
  microservices-network:
    driver: bridge
