spring:
  application:
    name: gateway-server

  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:7777}

  cloud:
    config:
      uri: ${CONFIG_SERVER_URL:http://localhost:7777}

logging:
  level:
    "[org.springframework.cloud.gateway]": INFO

management:
  endpoint:
    health:
      show-details: always
