spring:
  application:
    name: gateway-server

  config:
    import: optional:configserver:http://localhost:7777

  cloud:
    config:
      uri: http://config-server:7777

logging:
  level:
    "[org.springframework.cloud.gateway]": INFO

management:
  endpoint:
    health:
      show-details: always
