spring:
  application:
    name: enseignant-service

  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:${CONFIG_SERVER_URL:http://config-server:7777}}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
    registerWithEureka: true
    fetchRegistry: true

datasource:
  url: jdbc:mariadb://enseignant-db:3306/enseignant_db
  username: enseignant
  password: enseignant
  driver-class-name: org.mariadb.jdbc.Driver

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  database-platform: org.hibernate.dialect.MariaDBDialect

server:
  port: ${SERVER_PORT:8082}
